# Generated by Django 5.1.6 on 2025-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inactivo', 'Inactivo')], default='disponible', max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fila', models.IntegerField()),
                ('columna', models.CharField(max_length=5)),
                ('color', models.CharField(choices=[('530001', '#0094FF'), ('530013', '#00FF00'), ('530014', '#FF9900'), ('152001', '#9900FF'), ('320026', '#6600CC'), ('221003', '#FFD700'), ('390001', '#008080'), ('153001', '#FF66B2'), ('269001', '#FF0000'), ('186020', '#FF4500'), ('Desarrollo', '#FF0000'), ('Soporte', '#8B0000'), ('Selección', '#808000'), ('Leroy Merli', '#8A2BE2'), ('default', '#B0BEC5')], default='#B0BEC5', max_length=20)),
                ('piso', models.CharField(choices=[('PISO1', 'Piso 1'), ('PISO2', 'Piso 2'), ('PISO3', 'Piso 3'), ('PISO4', 'Piso 4'), ('TORRE1', 'Torre 1')], default='PISO1', max_length=50)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivos', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
