# Generated by Django 5.1.6 on 2025-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0002_alter_posicion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='color',
            field=models.CharField(default='#B0BEC5', max_length=20),
        ),
    ]
