# Generated by Django 5.1.6 on 2025-02-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0005_posicion_borde_alter_posicion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
