# Generated by Django 5.1.6 on 2025-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0006_alter_posicion_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='bordeDetalle',
            field=models.JSONField(default=dict),
        ),
    ]
