# Generated by Django 5.1.6 on 2025-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0007_posicion_bordedetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='borde',
            field=models.BooleanField(default=True),
        ),
    ]
