# Generated by Django 5.1.6 on 2025-03-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0009_posicion_bordedoble_posicion_colorfuente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicion',
            old_name='colorFuente',
            new_name='fontColor',
        ),
    ]
