# Generated by Django 5.1.6 on 2025-03-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0010_rename_colorfuente_posicion_fontcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicion',
            old_name='fontColor',
            new_name='colorFuente',
        ),
    ]
