# Generated by Django 5.1.6 on 2025-03-10 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0011_rename_fontcolor_posicion_colorfuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
