# Generated by Django 5.1.6 on 2025-03-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0013_alter_posicion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='colorOriginal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
