# Generated by Django 5.1.6 on 2025-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0015_remove_posicion_colororiginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='colorOriginal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
