# Generated by Django 5.1.6 on 2025-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0016_posicion_colororiginal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='borde',
        ),
        migrations.AlterField(
            model_name='posicion',
            name='colorOriginal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
